apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ${sriovnetworknodepolicy}
  namespace: ${operatornamespace}
spec:
  deviceType: netdevice
  isRdma: false
  mtu: ${mtu}
  nicSelector:
    pfNames:
    - ${nic}
    rootDevices:
    - "${pciid}"
  nodeSelector:
    ${NODESELECTOR}
  numVfs: ${numvfs}
  priority: ${priority}
  resourceName: ${sriovresourcename}
