apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-etc-udev-rules-d-11-nm-unmanaged-rules
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,${BASE64_UDEV_RULE}
          verification: {}
        filesystem: root
        group:
          name: root
        mode: 420
        path: /etc/udev/rules.d/11-nm-unmanaged.rules
        user:
          name: root
    systemd: {}
  osImageURL: ""