apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-test
  labels:
    app: sriov-test
spec:
  replicas: ${numworkers}
  selector:
    matchLabels:
      app: sriov-test
  template:
    metadata:
      labels:
        app: sriov-test
        k8s.v1.cni.cncf.io/networks: "${nic}"
    spec:
      containers:
        - name: samplepod
          command: ["/bin/sh", "-c", "trap : TERM INT; sleep 600000& wait"]
          image: alpine